# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_to_convert', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
