# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='file_to_convert',
            field=models.CharField(max_length=1000),
        ),
    ]
