# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_auto_20170213_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='file_to_convert',
            field=models.FileField(upload_to=''),
        ),
    ]
