# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0003_auto_20170213_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='file_name',
        ),
    ]
